### ISSUE TITLE
Error code on HRR cause by keyshare is confusing

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#101]
If a picotls server receives a client hello that does not contain an acceptable key share, it will correctly send back an HRR. However, in these conditions the "ptls_handshake" API returns PTLS_ERROR_IN_PROGRESS. This confusing, since in other HRR conditions the same API will return PTLS_ERROR_STATELESS_RETRY.
This is particularly confusing when doing QUIC, because "regular" Server Hello are sent in Handshake messages, but HRR should be sent in Stateless Retry messages.

**Comment by kazuho** [comment]
Thank you for raising the issue.

I agree that it is beneficial to provide a mode that utilizes a cookie when sending an HRR for a transport that provides stateless retry (e.g., QUIC).

Please review #102 and merge if it looks ok.
