### ISSUE TITLE
negotiating draft 28|27|26 does not work

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#137]
PR #134 implemented support for three draft versions, listing three values 0x7f1c, 0x7f1b and 0x7f1a in the "supported version" extensions. This works on the server side, because the server advertises support for the draft version selected by the client, but it does not appear to work on the client side. At least, it does not work when testing against WinQuic.

The TLS spec actually has a warning against negotiating draft versions in section 4.1.3.  Server Hello:
~~~
   RFC EDITOR: PLEASE REMOVE THE FOLLOWING PARAGRAPH Implementations of
   draft versions (see Section 4.2.1.1) of this specification SHOULD NOT
   implement this mechanism on either client and server.  A pre-RFC
   client connecting to RFC servers, or vice versa, will appear to
   downgrade to TLS 1.2.  With the mechanism enabled, this will cause an
   interoperability failure.
~~~

I wonder whether we should discuss that on the TLS list.

**Comment by kazuho** [comment]
My understanding is that the section you point to refers to "TLS 1.3 has a downgrade protection mechanism embedded in the server’s random value", not version negotiation as a whole.

**Comment by kazuho** [comment]
I would also argue that we are doing good by sending multiple draft versions.

We are actually greasing the Supported Versions extension by sending multiple versions, and have found an issue on one of the server implementations :-)

**Comment by huitema** [comment]
Yes, that's certainly one way to see it. Let's wait a bit to see how this evolves with other implementations.

**Comment by huitema** [comment]
Seems to be working fine.
