### ISSUE TITLE
Using 25519 with openssl version of picotls

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#143]
Is there a way to build picotls using the openssl version, but also enable support for 25519 and chacha20? This does not work by default, and is causing some issues in Quic trials.

**Comment by kazuho** [comment]
25519 is not (yet) supported by the OpenSSL backend. I am happy to review a PR once someone implements it.

OTOH, you can use both backends concurrently, by doing something like below.
```
ptls_key_exchange_algorithm_t *my_key_exchanges[] = {&ptls_minicrypto_x25519, &ptls_openssl_secp256r1, NULL};
```

We have always supported chacha20-poly1305 on the openssl backend when the backend has support for the cipher. Please see #49.

**Comment by huitema** [comment]
OK, I see how to define the key exchanges.
Don't I need to do something similar for ciphersuites?

**Comment by huitema** [comment]
With the additional ciphersuite, it seems to work.
