### ISSUE TITLE
picotls incorrectly sends missing_extension

### ISSUE THREAD

**Issue by xiaoyinl** [h2o/picotls#15]
If the client sends an empty key_share extension, picotls sends a missing_extension alert. It should send a Hello Retry Request instead. Wireshark packet file is attached.

[empty_key_share.zip](https://github.com/h2o/picotls/files/562922/empty_key_share.zip)

**Comment by kazuho** [comment]
Thank you for opening the issue.

Support for HelloRetryRequest is not yet complete. I will take care of this when we finish implementing it.

**Comment by kazuho** [comment]
I believe the issue has been fixed in 27a29f8, and the the HRR of picotls is working correctly against Canary.

Please let me know if the issue persists.
