### ISSUE TITLE
No certificate does not result in error

### ISSUE THREAD

**Issue by bkchr** [h2o/picotls#156]
When `client_authentication` is activated and the client does not provide any certificate, it just continues. I think that in this case an error should be thrown that a certificate is missing?

**Comment by kazuho** [comment]
I am not sure if I agree with that.

Per spec, client has the freedom to not send a certificate when server requests for one. See https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#rfc.section.4.4.2.4.

I'd assume that you can implement the necessary logic in the verify_certificate callback if you want to terminate the handshake in case no certificate is provided.

**Comment by bkchr** [comment]
Okay! Then I close this issue.
