### ISSUE TITLE
Assertion `server_name != NULL && "ptls_set_server_name MUST be called"

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#165]
Picotls has a default verifier for server certificate. That default verifier (verify_cert_chain) verifies that the server name is documented before calling openssl to check the chain. There is an assert for that at line 1008 in lib/openssl.c.

It is very clear that if the server name is not specified, verifying the cert chain is pointless. But then, we have lots of picoquic users who just want to test the transport features, and start a test with something like "picoquicdemo 127.0.0.1 4433", and then trigger the assert.

Is it possible to change the behavior and simply "return 0" if the server name is not specified? Or, do I need to just create my own version of the verifier that will bypass the tests in these cases?

**Comment by kazuho** [comment]
The correct thing to do here is to call `ptls_set_server_name` right after calling `ptls_new`, before calling `ptls_handshake`.

That would add the SNI extension (or maybe ESNI) to the ClientHello, which is a requirement of hq, and also provide the verifier the hostname that should be tested for.

**Comment by huitema** [comment]
I understand, and that's what Picoquic does when the application specifies a server name. But we have a use case when people just set up a test server with some random cert, or with a test cert, and attempt to connect by just specifying address and port.

The problem is that the verifier is set in the TLS context that is shared by multiple QUIC connections. I could specify a "null" verifier, but that's per context, not per connection.

**Comment by kazuho** [comment]
Thank you for the clarification. I think that now I understand the issue.

I have implemented proper certificate validation for IP address-based certificates in #166. With the PR, certificate validation should succeed when you use IP address as a method to specify the server, assuming that the server has a legitimate certificate being installed.

If you do not have a legitimate certificate, you should not verify the certificate (i.e. leave the verify callback to NULL).

Does that sound logical to you?

**Comment by huitema** [comment]
Yes, it is logical. The only problem is if there are several TLS connection at the client, and a single TLS context, and also a single callback. The need for callback is known pretty late, and at that point other callback choice may have been made for other connections.

**Comment by kazuho** [comment]
I see.

Then, I would suggest having your own verification callback that wraps the standard one.

The reason I suggest that is because I tend to think that the way a peer is verified is a property of the verifier rather than a connection.

Consider the case of the web browser. It doesn't ask you every time when you connect to a.b.c.d that returns an illegitimate certificate. Instead, it asks just once for the lifetime of the browser process. In other words, the verification strategy is kept in the verifier, that gets reset when the browser is restarted.

But if that is a real pain for you, I might not strongly oppose to adding a flag to handshake properties...

**Comment by huitema** [comment]
I think I will do that, wrap the standard verifier. When I looked at that it was a bit difficult because the verifier function is declared as "static".

We may want to have a set of different identifiers with different policies anyhow. For example, something like the SSH behavior may be adequate for many P2P applications.

**Comment by kazuho** [comment]
> When I looked at that it was a bit difficult because the verifier function is declared as "static".

I would suggest sticking to using the public interface. I believe that it can be as simple as follows:
* call `ptls_openssl_init_verify_certificate` during setup
* in your wrapping `verify_certificate` callback:
  * determine if you want to verify the certificate:
     * if yes:
       * call `ptls_openssl_verify_certificate_t::super.verify_certificate` to obtain the verify_sign callback and verify_data, and return them so that the callback will be called when receiving CertificateVerify
     * if no:
       * set `verify_cb` to NULL to make processing of CertificateVerify a noop

> We may want to have a set of different verifiers with different policies anyhow. For example, something like the SSH behavior may be adequate for many P2P applications. And a NULL verifier may be adequate for the folks doing simple lab tests.

Agreed.

**Comment by huitema** [comment]
Solved for now. I just make sure that the verifier is NULL if the server name is not specified.
