### ISSUE TITLE
mini crypto not found?

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#180]
The compile scripts for Picoquic are failing because of a Picotls depency:
```
-- Found picotls-core at : /home/travis/build/private-octopus/picotls/libpicotls-core.a 
-- Found picotls-crypto at : PTLS_MINICRYPTO-NOTFOUND 
-- Found picotls-openssl at : /home/travis/build/private-octopus/picotls/libpicotls-openssl.a 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1f") 
root: 
OpenSSL_VERSION: 1.0.1f
OpenSSL_INCLUDE_DIR: /usr/include
OpenSSL_LIBRARIES: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PTLS_MINICRYPTO
```
Is this a known issue?

**Comment by kazuho** [comment]
No it is not.

I wonder if it is an issue in picoquic, because picotls never uses a variable named PTLS_MINICRYPTO in CMakeLists.txt.

**Comment by huitema** [comment]
PTLS_MINICRYPTO is the environment variable that our scripts fill when they have found the library "picotls-minicrypto". This is a travis build, using clang and scan-build. When trying a clean clang build, I get some errors:
```
clang: error: unsupported argument 'fuzzer' to option 'fsanitize='
CMakeFiles/fuzzer-asn1-validation.dir/build.make:62: recipe for target 'CMakeFiles/fuzzer-asn1-validation.dir/fuzz/fuzzer-asn1-validation.c.o' failed
make[2]: *** [CMakeFiles/fuzzer-asn1-validation.dir/fuzz/fuzzer-asn1-validation.c.o] Error 1
CMakeFiles/Makefile2:253: recipe for target 'CMakeFiles/fuzzer-asn1-validation.dir/all' failed
make[1]: *** [CMakeFiles/fuzzer-asn1-validation.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kazuho** [comment]
The error looks like that the clang is too old and lacks support for the `-fsanitize` option.

I think that there is no need to build fuzzer when picotls is being used as a dependency; #181 resolves the issue by adding a flag that _optionally_ builds the fuzzer.

Would you mind checking if the fix has resolved your issue?

**Comment by huitema** [comment]
Yes, the build is passing now. The dependency on the fuzzer caused the build to fail before the mini crypto could be built. Thanks for the fix.
