### ISSUE TITLE
Support ESNI

### ISSUE THREAD

**Issue by candrews** [h2o/picotls#187]
Encrypted SNI is on the standards track and is already being deployed by big players.

Draft RFC: https://tools.ietf.org/html/draft-ietf-tls-esni

Championed by the EFF: https://www.eff.org/deeplinks/2018/09/esni-privacy-protecting-upgrade-https
Deployed by Cloudflare: https://blog.cloudflare.com/esni/
Cloudflare's technical details post: https://blog.cloudflare.com/encrypted-sni/
Supported by Firefox: https://blog.mozilla.org/security/2018/10/18/encrypted-sni-comes-to-firefox-nightly/
Supported by NSS: https://bugzilla.mozilla.org/show_bug.cgi?id=1495120
ESNI is specifically being pushed by Sen. Ron Wyden (D-OR): https://gizmodo.com/sen-wyden-urges-dhs-to-adopt-new-encryption-tech-to-pr-1830001179

I noticed that there's a work in progress PR: h2o/picotls#155

**Comment by kazuho** [comment]
Thank you for opening the issue. As one of the authors of the draft, I am sure we will support ESNI.

**Comment by kazuho** [comment]
#155 has been merged.
