### ISSUE TITLE
improve (or provide hook to customize) 0-RTT ticket replay detection

### ISSUE THREAD

**Issue by kazuho** [h2o/picotls#208]
The rule we have now is very lax. We accept 0-RTT unless we see an unexpectedly old ticket (i.e., issued more than 10 seconds ago).
```
            int64_t delta = (now - issue_at) - (identity->obfuscated_ticket_age - age_add);
            if (delta <= PTLS_EARLY_DATA_MAX_DELAY)
                *accept_early_data = 1;
```

This is fine when the `max_early_data_size` is small (compared to the size of the TCP receive buffer) and if the application protocol has a way to delay the processing of 0-RTT data (e.g., HTTP 425).

However, considering the fact that picotls might be used for application protocols other than HTTP, it's worth considering tightening the limits (we do not check the lower bound at all!), or providing a hook to customize reuse detection.

**Comment by huitema** [comment]
The other issue with the code is that it can roll over...

**Comment by huitema** [comment]
Look at:
```
delta_age = ((uint32_t)ticket-age - (uint32_t)age_add);
```
If it is implemented as:
```
delta_age = (int32_t)((uint32_t)ticket-age - (uint32_t)age_add);
```
Then you can obtain any value between -2^31 and 2^31-1.

**Comment by kazuho** [comment]
I am not sure if I agree that delta_age is a signed int type. My understanding is that it is `uint32_t` that gets promoted to `uint64_t` right before subtraction.

If we look at the operands of the outermost `-` operator, LHS is `(now - issue_at)` (of type uint64_t) and RHS is `(identity->obfuscated_ticket_age - age_add)` (of type uint32_t). Because both the operands are unsigned types, RHS gets promoted to that of the LHS (i.e. uint64_t), and subtraction between uint64_t is calculated. Then, the value is converted to `int64_t` when the assignment to `delta` happens.

**Comment by huitema** [comment]
I just wrote a small test:
```
(f4240 - 0) - (1fffffff - 0) = ffffffffe00f4241 (-535870911)
(f4240 - 0) - (3fffffff - 0) = ffffffffc00f4241 (-1072741823)
(f4240 - 0) - (5fffffff - 0) = ffffffffa00f4241 (-1609612735)
(f4240 - 0) - (7fffffff - 0) = ffffffff800f4241 (-2146483647)
(f4240 - 0) - (9fffffff - 0) = ffffffff600f4241 (-2683354559)
(f4240 - 0) - (bfffffff - 0) = ffffffff400f4241 (-3220225471)
(f4240 - 0) - (dfffffff - 0) = ffffffff200f4241 (-3757096383)
(f4240 - 0) - (ffffffff - 0) = ffffffff000f4241 (-4293967295)
```
So, yes, we can end up with very large negative numbers...

**Comment by kazuho** [comment]
@huitema That's completely fine.

In case of the first line, the reported age of the ticket is 0x1fffffff milliseconds (6.2 days). OTOH, the actual age is 1000 seconds. `delta` becomes -535870911 milliseconds.

Because it is _not_ likely that the session ticket is "replayed"<sup>1</sup>, we accept 0-RTT.

[1] We consider a ticket to be potentially replayed when it is used more than 10 seconds _after_ when the ticket claims itself to be used.

**Comment by huitema** [comment]
I think I can play different games with different values. Is it correct to assume that when you issue the ticket, the internal "age_add" value is the same as the obfuscated ticket age visble to the application?

**Comment by kazuho** [comment]
@huitema Yes. "age_add" is the NewSessionTicket.ticket_age_add value defined in RFC 8446.

**Comment by huitema** [comment]
OK. Here is another version of the same test. The time "now" is 1000000 above the issue time, which means more than the default 100000 interval. The "obfuscated ticket age" is put to some random values by the application:
```
(f4240 - 0) - (c8f8f0a7 - c8f8f0a7) = f4240 (1000000)
(f4240 - 0) - (e8f8f0a6 - c8f8f0a7) = ffffffffe00f4241 (-535870911)
(f4240 - 0) - (8f8f0a5 - c8f8f0a7) = ffffffffc00f4242 (-1072741822)
(f4240 - 0) - (28f8f0a4 - c8f8f0a7) = ffffffffa00f4243 (-1609612733)
(f4240 - 0) - (48f8f0a3 - c8f8f0a7) = ffffffff800f4244 (-2146483644)
(f4240 - 0) - (68f8f0a2 - c8f8f0a7) = ffffffff600f4245 (-2683354555)
(f4240 - 0) - (88f8f0a1 - c8f8f0a7) = ffffffff400f4246 (-3220225466)
(f4240 - 0) - (a8f8f0a0 - c8f8f0a7) = ffffffff200f4247 (-3757096377)
```
The first line will cause a reject as expected. The other ones will pass the test. That seems bad.

**Comment by kazuho** [comment]
> The other ones will pass the test. That seems bad.

That's because the reported ticket age is greater than the true ticket age in all those cases.

For example, e8f8f0a6 - c8f8f0a7 = 1fffffff > f4240. Or (8f8f0a5 - c8f8f0a7) & UINT32_MAX = 3ffffffe > f4240.

**Comment by kazuho** [comment]
I think that the test would fail if you supply something like: `(f4240 - 0) - (c8f8f1a7 - c8f8f0a7)` (i.e. reported age being 0x100 milliseconds where the true age is f4240).

**Comment by huitema** [comment]
So I went back to the text of RFC 8446. It says:
```

   For PSKs provisioned via NewSessionTicket, a server MUST validate
   that the ticket age for the selected PSK identity (computed by
   subtracting ticket_age_add from PskIdentity.obfuscated_ticket_age
   modulo 2^32) is within a small tolerance of the time since the ticket
   was issued (see Section 8).  If it is not, the server SHOULD proceed
   with the handshake but reject 0-RTT, and SHOULD NOT take any other
   action that assumes that this ClientHello is fresh.
```
The purpose of that check is to enable verification of single usage of 0-RTT tickets, as stated in:
```
   An alternative form of anti-replay is to record a unique value
   derived from the ClientHello (generally either the random value or
   the PSK binder) and reject duplicates.  Recording all ClientHellos
   causes state to grow without bound, but a server can instead record
   ClientHellos within a given time window and use the
   "obfuscated_ticket_age" to ensure that tickets aren't reused outside
   that window.
```
That means that the client is supposed to update the "obfuscated ticket age", setting the new value to:
```
obfuscated_new = obfuscated_received + (now - ticket_received)
```
TLS servers may or may not actually implement the 0RTT anti replay protections, but they should verify that the client is setting the obfuscated_received data "by the rules". If attackers copy a 0-RTT message and replay it later, they will not be able to change to obfuscated value, so they will fail the check. The rule is really about detecting replays after a short time. That means the code really should be:
```
            int64_t delta = (now - issue_at) - (identity->obfuscated_ticket_age - age_add);
            if (delta <= PTLS_EARLY_DATA_MAX_DELAY && -delta >=  PTLS_EARLY_DATA_MAX_DELAY )
                *accept_early_data = 1;
```
The constant `PTLS_EARLY_DATA_MAX_DELAY` should be set to the maximum drift of the sender and receiver clock over the validity interval of the ticket. Assuming a ticket validity time of 7 days, that drift ought to be very small -- a minute should be enough in most cases, 5 minutes should be really a lot.

**Comment by kazuho** [comment]
> That means the code really should be:

I think what you meant is: `-PTLS_EARLY_DATA_MAX_DELAY <= delta  && delta <= PTLS_EARLY_DATA_MAX_DELAY`.

I am fine to take that change if that makes people feel safer, though I do not think there is a necessity to make the change, because I assume that in practice all the clients that we care would have a good clock so that they wouldn't initiate a resumption that contains a ticket age that is too small.

> Assuming a ticket validity time of 7 days, that drift ought to be very small -- a minute should be enough in most cases, 5 minutes should be really a lot.

That's going to increase the replay window for clients that have precise clock. The window we currently enforce for those clients is 10 seconds. I think I might prefer penalizing endpoints that have an inaccurate clock, rather than enlarging the replay window.

**Comment by kazuho** [comment]
To rephrase current code enforces a 10 second window when endpoints have accurate clocks, but does not provide protection when either of the nodes have a broken clock,

Changing the window to +-10 seconds will provide protection when the clocks are broken, without having a negative impact on communication between endpoints with accurate clocks. Therefore I am happy to make the change.

Changing it to +-1 minute (or 5) is widening the window, I’m not sure if I like it.

**Comment by huitema** [comment]
I am fine with keeping 10 seconds. The net effect is that adversaries will only have a window 20 second to replay client hello and 0-rtt packets, and that's good.
