### ISSUE TITLE
Improve existing fuzz targets

### ISSUE THREAD

**Issue by jfoote** [h2o/picotls#221]
The existing `fuzz-asn1-type-and-length` and `fuzz-asn1-validation` fuzz targets are [too small](https://github.com/google/oss-fuzz/pull/2229) for continuous fuzzing via oss-fuzz. We should:

- consider combining these targets so that they can be instrumented with enough edge counters to justify continuous fuzzing
- investigate adding a seed file corpus/corpora
- tune oss-fuzz params for fuzz targets

One we have seed files for all targets we could also consider running each fuzz target with a single input as part of CI, though that could be slightly out-of-scope here.

**Comment by deweerdt** [comment]
> consider combining these targets so that they can be instrumented with enough edge counters to justify continuous fuzzing

I've addressed this in https://github.com/h2o/picotls/pull/224, thank you.

**Comment by jfoote** [comment]
This was fixed in #224
