### ISSUE TITLE
ESNI documentation

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#242]
I would like to start implementing ESNI in Picoquic. Where can I start?

**Comment by kazuho** [comment]
@huitema PTAL: https://github.com/h2o/picotls/wiki/ESNI-support-in-picotls

**Comment by huitema** [comment]
Looking at it. I will try follow the instructions and develop that in Picoquic.

On the client side, I understand that the client should provide the content of the ESNI record to the stack. Is that correct?

**Comment by kazuho** [comment]
> On the client side, I understand that the client should provide the content of the ESNI record to the stack. Is that correct?

Correct. picotls does *not* depend on libresolv. It is the application's responsibility to obtain a ESNI Resource Record and set it to `ptls_handshake_properties_t::client::esni_keys`.

**Comment by huitema** [comment]
I did the first step -- porting picotls-esni to Windows. That's PR #244. Next is integrating that in picoquic.

Note that calling the output an "ESNI Record" is ambiguous. I assume you mean the 
```
3.3.14. TXT RDATA format

    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    /                   TXT-DATA                    /
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+

where:

TXT-DATA        One or more <character-string>s.
```
Per RFC 1035, this is a "character string". It can carry binary just fine, but it needs to be escaped before being inserted in the DNS zone file. I added an option (-a) to output the record in zone file format.

**Comment by huitema** [comment]
@kazuho I am looking at the details of the "picotls-esni" program, and I see that it does not take a "published SNI" parameter. That seems wrong. Should I fix it?

**Comment by huitema** [comment]
I also see that `ptls_esni_init_context()` does not expect the published SNI value. Is that because you are implementing an older version of the ESNI draft?

**Comment by huitema** [comment]
I think it is easy to handle the latest draft version. There are four changes:
1) In esni.c in the "emit-esni" function, add a parameter to pass the "published sni", and of course encode it.
2) In picotls.c, in "parse_esni_keys", skip over the published-sni field.
3) In picotls.c, in "ptls_esni_init_context", skip over the published-sni field.
4) In picotls.c, add a public function "get_published_sni(esni_rr, buf)" so clients can easily get the proposed public SNI.

But I see that the server's esni extension's syntax also changes with the new version. So there may be more

**Comment by huitema** [comment]
I am also looking at supporting the "split server" scenario. Clearly, that's not what the code does...

**Comment by kazuho** [comment]
Yes, the reason we do not have published-sni is because we our code at the moment implements -02.

> 1. In esni.c in the "emit-esni" function, add a parameter to pass the "published sni", and of course encode it.

Yes.

> 2. In picotls.c, in "parse_esni_keys", skip over the published-sni field.

I think you might want to return the value of published-sni field from the function up to `send_client_hello`, so that SNI extension can be filled with the value found in the ESNI RR.

> 3. In picotls.c, in "ptls_esni_init_context", skip over the published-sni field.

Yes.

> 4. In picotls.c, add a public function "get_published_sni(esni_rr, buf)" so clients can easily get the proposed public SNI.

I do not think you need it, please see my comment on point 2.

**Comment by kazuho** [comment]
> I am also looking at supporting the "split server" scenario. Clearly, that's not what the code does...

I think you can use picotls as-is to implement "split server". What you'd do is feed ClientHello into picotls while retaining the bytes that you have received, observe the value of ESNI, then send the bytes you've received to the backend server.

**Comment by huitema** [comment]
Looking at the details of the APIs. On the server side, the context is set with the call to
```
int ptls_esni_init_context(ptls_context_t *ctx, ptls_esni_context_t *esni, ptls_iovec_t esni_keys,
                           ptls_key_exchange_context_t **key_exchanges)
```
The sample code in `t/util.h` code declares the content of `esni_keys` and the pointer array `key_exchanges` on the the stack. Is it OK to assume that these data will not be reused after the call?

Also, the sample code takes just one RR from a file. I assume that we could have several of those, and provide a null terminated pointer list in `ctx->esni`. Is that correct?

**Comment by kazuho** [comment]
> The sample code in `t/util.h` code declares the content of `esni_keys` and the pointer array `key_exchanges` on the the stack. Is it OK to assume that these data will not be reused after the call?

The assumption is that the caller of the `setup_esni` function owns and retains the list of key exchanges for the lifetime of the context. In case of `t/cli.c`, the list is a local variable of `main`, therefore it satisfies the requirement.

> Also, the sample code takes just one RR from a file. I assume that we could have several of those, and provide a null terminated pointer list in `ctx->esni`. Is that correct?

Correct.

**Comment by huitema** [comment]
OK. I think that means that the owner is also in charge of freeing the list of key exchanges  when freeing up the server context. Will do that.

**Comment by huitema** [comment]
Still trying to understand memory allocation and resource disposal. Looking at the source, I see that 
`void ptls_esni_dispose_context(ptls_esni_context_t *esni)` calls 
```
esni->key_exchanges[i]->on_exchange(esni->key_exchanges + i, 1, NULL, ptls_iovec_init(NULL, 0));
```
I think this has two implications for me:

1) In my own resource disposal, I should free the key exchange pointer array, but I should not bother trying to free the individual array elements
2) If I initialize several ESNI contexts using the same `key_exchange` array, there might be a double free of the exchange contexts

**Comment by kazuho** [comment]
Thanks for pointing that out. I think it's a bug.

IMO, `key_exchanges` of `ptls_esni_context_t` should be handled the same way as that of `ptls_context_t` is handled, meaning that the ownership of the null-terminated array and the lifetime of the objects within the array should be controlled by the application, not picotls.

**Comment by huitema** [comment]
I think I have a working implementation in picoquic based on the docs, but I am missing a status API on the client side. How does the client know that ESNI negotiation was successful?

**Comment by huitema** [comment]
Damn. I have an issue with real time processing. The "not before" time in the RR is set to "now" by picotls-esni, the life-time is set to "90 days", but the test program is running in virtual time...

**Comment by huitema** [comment]
Success. I set the virtual time in the picoquic tests to the middle of the "before" and "after" time in the RR. That plus a few other fixes, and the tests are now passing.

But they also pass on Linux, and they should not. This is because of the behavior of the Picotls code, which simply reacts to ESNI errors by not doing ESNI, silently. I need an API to check that ESNI actually succeeded!

**Comment by huitema** [comment]
@kazuho: I am proposing two changes:

1) Move the definition of the ESNI secret to the public header, "./include/picotls.h"

2) Add an API to get the ESNI secret.

I need that in the tests, to check that the negotiation actually worked, and also in the "authenticated handshake" implementation.

**Comment by huitema** [comment]
Note that the verification is complex -- the server parameters are only visible inside the OnClientHello callback, and the client parameters are erased once the encrypted extension is received. But it does work, and I can see the same esni nonce on both sides.

**Comment by huitema** [comment]
@kazuho Now that the ECH/ESNI is nearly complete, we should consider implementing ECH in picotls. Are you working on that, or should I do it?
