### ISSUE TITLE
Add Private key methods support!

### ISSUE THREAD

**Issue by patrickkh7788** [h2o/picotls#265]
Is three a plan to support Private key methods like https://github.com/rperper/picotls ?

```c
enum ptls_private_key_result_t (*sign)(ptls_sign_certificate_t *do_sign,
                                           ptls_t *tls,
                                           uint16_t *selected_algorithm,
                                           ptls_buffer_t *output,
                                           ptls_iovec_t input,
                                           const uint16_t *algorithms,
                                           size_t num_algorithms);
```

With this function, maybe the private key can be storage at remote server, like Clouldflare keyless https://www.cloudflare.com/ssl/keyless-ssl/

**Comment by kazuho** [comment]
The current API already supports key separation.

The openssl backend of picotls uses the EVP interface provided by OpenSSL (libcrypto), and we have an EVP engine that runs on a separate process (https://github.com/h2o/neverbleed/). You can combine the two.

**Comment by patrickkh7788** [comment]
Thansk for explain, I will try neverbleed.  (I guess it is for process, not cross network)
