### ISSUE TITLE
question about ptls_get_record_overhead function

### ISSUE THREAD

**Issue by Simon-Zh-0409** [h2o/picotls#276]
Hello, I'm a little confused about ptls_get_record_overhead function, from my understanding, the payload_size + overhead should be equal to buf->off. But, I found ptls_get_record_overhead function always return 22, but when I use a 100258 payload size, the buf->off will be 100412. Could you give me some instructions? Appreciate in advance.

**Comment by kazuho** [comment]
`ptls_get_record_overhead` returns the overhead per TLS record. IIRC TLS record cannot exceed 16KB. If the amount of data that you want to send is bigger than that, the output would be split into multiple records, each of them having 22 bytes of overhead.

**Comment by Simon-Zh-0409** [comment]
Thanks, that helps a lot.
