### ISSUE TITLE
Travis builds of Picotls fail on Mac OS

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#280]
As part of testing new versions of picoquic, we run Travis tests on a variety of platforms.

Recently, the tests on MAC OS have started failing because Picotls could not be built. An example would be: https://travis-ci.org/private-octopus/picoquic/jobs/615409697. The key message is:
```
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):

  Could NOT find PTLS (missing: PTLS_OPENSSL_LIBRARY)
```
Before launching CMake, the scrip defines:
```
$ export CMAKE_OPTS=" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"
```

**Comment by kazuho** [comment]
Would it be possible for your tests to install openssl using brew? The path is based on the presumption that that would be done.

As a maintainer of picotls, I think we should retain that dependency in picotls tests, so that we can guarantee the openssl backend to be tested on macOS.

**Comment by huitema** [comment]
I am not sure that I know how to trigger a brew install for Mac OS on Travis. The compile works for the version `macOS (xcode)`, but does not for `macOS (xcode 10.1/clang-10)`

**Comment by huitema** [comment]
I think that openssl is correctly installed. The missing variable is "PTLS_OPENSSL_LIBRARY", and I don't know how to set that.

**Comment by huitema** [comment]
Just got the same issue with another PR: https://travis-ci.org/private-octopus/picoquic/builds/615897073?utm_medium=notification&utm_source=email

There are 2 builds on Mac OS, the only difference being the compiler. One works, one does not. This is very bizarre.

**Comment by huitema** [comment]
@kazuho: I have done some more investigation, and I am hitting a wall. I added to the script the command:
```
/usr/local/opt/openssl/
```
The command runs, and then gives a warning:
```
Warning: openssl@1.1 1.1.1d is already installed and up-to-date
To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
```
But then the library is not at the expected location:
```
ls: /usr/local/opt/openssl/: No such file or directory
```
Do you have an idea how to fix that?

**Comment by huitema** [comment]
@kazuho: solved. The fix was to run `brew reinstall openssl`, which places a new copy at the expected location.

**Comment by kazuho** [comment]
Good to know that you've identified the issue.

So it's the case that the "brew"-ed version of OpenSSL is missing. Based on that knowledge, I've went with cef6614 (see https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos).
