### ISSUE TITLE
ptls_openssl_dispose_verify_certificate doesn't work for static objects

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#286]
`ptls_openssl_dispose_verify_certificate` seems to assume that passed the object is dynamically allocated (because it tries to free it). That's a problem, because `ptls_openssl_init_verify_certificate` works just fine with a static object.

The result is that with a static object one needs to call `X509_STORE_free` in order to prevent leaks, since calling `ptls_openssl_dispose_verify_certificate` crashes due to the `free` call.

**Comment by kazuho** [comment]
Thank you for reporting the issue, sorry for the belated response. You are absolutely correct. Fixed in the commit above.
