### ISSUE TITLE
Reduce stack usage

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#298]
There are several function in picotls that use large stack-allocated data structures, which is a bit of an issue on low-capability devices. `server_handle_hello`, for example, uses 1512 bytes of stack space, and many others use more than 100 bytes:
```
server_handle_hello                     1512  static
client_handle_new_session_ticket        624   static
hkdf_expand_label                       584   static
handle_client_handshake_message         368   static
ptls_handshake                          352   static
send_certificate_and_certificate_verify 320   static
handle_certificate_verify               304   static
build_esni_contents_hash                304   static
send_client_hello                       296   static
ptls_export_secret                      232   static
handle_certificate                      208   static
secp256r1sha256_sign                    176   static
log_secret                              176   static
update_traffic_key                      128   static
new_aead                                128   static
calc_verify_data                        128   static
create_esni_aead                        120   static
ptls_hkdf_expand                        104   static
handle_input                            96    static
verify_finished                         88    static
```
It would be great if that could be reduced somehow.

A lot of this seems to be due to encoding/decoding buffers. Would you be open to using a shared global buffer for this across functions? It would obviously kill thread-safety.

Another option could be to change the API so that suitably-sized buffers need to be passed as arguments, but this further complicates the API, which for many functions already has a lot of arguments.

**Comment by larseggert** [comment]
The cifra binding has some additional functions of concern:
```
sha384_final                            216   static
sha256_final                            120   static
chacha20poly1305_init                   96    static
x25519_key_exchange                     56    static
```

**Comment by kazuho** [comment]
@larseggert Thank you for filing the issue. Could you please check if #315 works for you?

In addition it might be a good idea to add knobs to change the exponential backoff strategy used by `ptls_buffer_reserve`. At the moment, it starts from 1,024 bytes and does a 2x back-off. I am happy to see a PR that changes one or both of these constants from hard-coded values to `#ifndef ... #define #endif` constants, so that users can override them by using compile options.

**Comment by larseggert** [comment]
Thank you! This seems to make a huge difference, and all my tests still work.

**Comment by larseggert** [comment]
Regarding `ptls_buffer_reserve`, since that is heap usage, it's not that critical. Many of these embedded platforms have an OK amount of heap, but keep the stack pretty small.
