### ISSUE TITLE
Draft format on supported_versions

### ISSUE THREAD

**Issue by alagoutte** [h2o/picotls#3]
Hi,

i working on TLS 1.3 implementations and try the tool for check if it is good...

And found a issue about draft format
I get : 
            Extension: supported_versions (len=3)
                Type: supported_versions (43)
                Length: 3
                Supported Versions length: 2
                Supported Versions: Unknown (0x7f16)

The problem is about 0x07<draft number>
With Firefox nighty build, the draft number is "encoded using hexa"
            Extension: supported_versions (len=9)
                Type: supported_versions (43)
                Length: 9
                Supported Versions length: 8
                Supported Versions: TLS 1.3 (draft 16) (0x7f10)
...
(Google Chrome Canary, use 0x0f0e for draft 14 ?)

I have check the draft spec (4.2.1.1. Draft Version Indicator)  and it is no indicate the format

**Comment by alagoutte** [comment]
See https://github.com/tlswg/tls13-spec/issues/682

**Comment by kazuho** [comment]
Thank you for noticing the issue as well as confirming to the spec. authors. Fixed in the above commit.

Also, I am delighted to know that Firefox Nightly supports draft 16. I have been having a hard time to find an implementation that can be used for interoperability testing.

**Comment by alagoutte** [comment]
Thanks for quick fix (your implementation found a issue on my dissector code...)
