### ISSUE TITLE
Issue with gcc-4.9 since PTLS_ELEMENTSOF merge

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#303]
A bunch of errors like this:
```
/home/travis/build/NTAP/quant/lib/deps/picotls/lib/picotls.c: In function ‘is_supported_version’:
/home/travis/build/NTAP/quant/lib/deps/picotls/lib/picotls.c:382:5: error: size of unnamed array is negative
     for (i = 0; i != PTLS_ELEMENTSOF(supported_versions); ++i)
```

**Comment by kazuho** [comment]
Sorry for the inconvenience.

By testing at https://godbolt.org/z/8_B9fC, it seems that `__builtin_compatible_types_p` of GCC versions before 5.4 do not yield the expected value. I will add workaround for those versions.
