### ISSUE TITLE
./picotls.c int ptls_send(ptls_t *, ptls_buffer_t *, const void *, size_t): Assertion `tls->traffic_protection.enc.aead != NULL' failed.

### ISSUE THREAD

**Issue by phpstatic** [h2o/picotls#307]
hi @kazuho,

Thanks for this nice open source projects, I am try use it as tls1.3 client code and it work great on my developer process.

how ever, when I  try deploy my app into production, I get this assertion error when reuse the session ticket :

```sh
./picotls.c: int ptls_send(ptls_t *, ptls_buffer_t *, const void *, size_t): Assertion `tls->traffic_protection.enc.aead != NULL' failed.
```

When server send `Server Hello, Change Cipher Spec` for new session,  reuse that ticket will tigger this error. (in this case,  handle_client_handshake_message get called two times,  I test with 2 stored ticket and they both throw this error).

I try print the 2 stored ticket cipher_suite_id and key_shared_id(save_ticket save  2 ticked when server send send `Server Hello, Change Cipher Spec`),   there shared same PTLS_CIPHER_SUITE_AES_256_GCM_SHA384 and PTLS_GROUP_X25519. 

correct me if I am wrong, in this case the second ticket should use a different cipher_suite id key_shared_id pair?

Thanks in advance for this great work.

Kind Regards

**Comment by phpstatic** [comment]
I fix this issue by myself.  turn out I need check `tls->client.using_early_data` before send early data, after call first ptls_handshake.

This cost me a lot time since no wiki content talk about this, and I send private email to  @kazuho ask him help( a small tips or reject will be ok),  never get any response.

He has no obligation to help me or anyone,  but anyone should know you are all on yourself.

Check the issues related to bugs or questions( without feature request):

https://github.com/h2o/picotls/issues/279
https://github.com/h2o/picotls/issues/260
https://github.com/h2o/picotls/issues/245
https://github.com/h2o/picotls/issues/268
https://github.com/h2o/picotls/issues/163
https://github.com/h2o/picotls/issues/142
https://github.com/h2o/picotls/issues/140

**Comment by kazuho** [comment]
Sorry for the belated response. FWIW, the correct thing to do is to consult `ptls_handshake_properties_t::client.max_early_data_size`. Even when 0-RTT can be used, it does not necessarily mean that the client can send arbitrary amount of data. Therefore, you cannot rely on `tls->client.using_early_data`.
