### ISSUE TITLE
core dump running server

### ISSUE THREAD

**Issue by tmshort** [h2o/picotls#33]
Using apps/server.pem from openssl:master branch:

./cli -c server.pem -k server.pem 127.0.0.1 4433

#0  do_lookup_x (new_hash=new_hash@entry=4245278497, old_hash=old_hash@entry=0x7ffcd3297ba0, 
    result=result@entry=0x7ffcd3297bb0, scope=<optimized out>, i=i@entry=0, flags=flags@entry=1, 
    skip=skip@entry=0x0, undef_map=undef_map@entry=0x7f5b6cebb1c8) at dl-lookup.c:98
#1  0x00007f5b6cca1961 in _dl_lookup_symbol_x (undef_name=0x401cd2 "fclose", undef_map=0x7f5b6cebb1c8, 
    ref=ref@entry=0x7ffcd3297c68, symbol_scope=0x7f5b6cebb520, version=0x7f5b6ce91600, 
    type_class=type_class@entry=1, flags=1, skip_map=skip_map@entry=0x0) at dl-lookup.c:737
#2  0x00007f5b6cca6527 in _dl_fixup (l=<optimized out>, reloc_arg=<optimized out>) at ../elf/dl-runtime.c:111
#3  0x00007f5b6ccad4d5 in _dl_runtime_resolve () at ../sysdeps/x86_64/dl-trampoline.S:45
#4  0x0000000000403a6f in main (argc=7, argv=0x7ffcd3298118) at /home/tshort/picotls/git/picotls/t/cli.c:463

Including only the appropriate data type in the argument files doesn't matter.
This is crashing on case 'c', reversing the arguments ('k' first) still crashes at case 'c'.
Running on: Linux my-linux 3.13.0-110-generic #157-Ubuntu SMP
OpenSSL 1.0.1f 6 Jan 2014

**Comment by kazuho** [comment]
Thank you for reporting the issue. Fixed in above commit.
