### ISSUE TITLE
TLS complete signal?

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#354]
In picoquic, we observe that the TLS context accounts for a large part of the per connection memory. It is tempting to delete it once the session is established, at least on servers that manage a large number of connections. But doing so risks discarding post handshake messages, such as session resume tokens. The ideal would be to get a some kind of "TLS complete" signal from picotls, when all the post handshake messages have been sent or received. Is that something we can do?

**Comment by kazuho** [comment]
Left some comments on the other issue, but a server can send TLS session tickets at any given moment. Therefore, TLS context cannot be discarded without taking some risk. Also, I do not think that the size of `ptls_context_t` is large enough to become a concern. It's only ~512 bytes.

**Comment by huitema** [comment]
I managed to solve the picoquic issue without having to delete the TLS context.
