### ISSUE TITLE
Verifying certificate purpose

### ISSUE THREAD

**Issue by twirtgen** [h2o/picotls#368]
When establishing connection with a TLS server, I think `X509_VERIFY_PARAM_set_purpose` does not check the right purpose.

Currently, when picotls is used as a client, the line: https://github.com/h2o/picotls/blob/80a2bbd8da935c5af6c713d0711d27b4fb7dbae0/lib/openssl.c#L1235 checks if the key can be used to authenticate an SSL client.

However, as I understand it, they have to check `X509_PURPOSE_SSL_SERVER` instead, since the certificate has been sent by the server.

There were conversations about this in https://github.com/openssl/openssl/pull/14199#diff-7c61ad18e76872e1f37a7874c71cc8b3508af9e481530896b57315602daf5835R458 (https://github.com/openssl/openssl/pull/14199/files#diff-c17351bdef7704fb7ac7fa0cf992ff9cf68167a1b66d7aa63670496c7af9a6a6R109) and in https://github.com/openssl/openssl/issues/13965#issuecomment-777499874.

**Comment by kazuho** [comment]
Thank you for reporting the issue!
