### ISSUE TITLE
Support for ECH

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#378]
Does Picotls support the latest ECH draft?

**Comment by imsys** [comment]
Draft 15 was implemented, https://github.com/h2o/picotls/pull/437
And from there were no change from [draft 15 to 16](https://author-tools.ietf.org/iddiff?url1=draft-ietf-tls-esni-15&url2=draft-ietf-tls-esni-16&difftype=--html), it was just a keep-alive version bump, so Picotls does support the latest draft-16.

**Comment by kazuho** [comment]
Thank you for the followup. That is correct.
