### ISSUE TITLE
unable to build with openssl1.1 on windows

### ISSUE THREAD

**Issue by hd51515** [h2o/picotls#412]
[ptlsvserrorwithopenssl111.txt](https://github.com/h2o/picotls/files/9478397/ptlsvserrorwithopenssl111.txt)

**Comment by huitema** [comment]
@hd51515 I think that PR #413 solves your issues. Can you verify please?

**Comment by huitema** [comment]
@hd51515 I had to delete PR #413 because of GitHub issues. Please try PR #415 instead.

**Comment by huitema** [comment]
Close as PR #415 is merged.
