### ISSUE TITLE
ptls_handshake() returns data after ServerHello

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#50]
On the client side, once I feed the ServerHello data into `ptls_handshake()`, it returns zero (indicating that the handshake is done) but *also* returns 58 bytes of data in `sendbuf`. What is that data? According to the example code on the wiki, that shouldn't happen?

**Comment by kazuho** [comment]
It's ClientFinished, assuming that you are talking about a client-side of the TLS connection receiving a messages sent from server-side starting from ServerHello to ServerFinished.

I think that the case is covered in the example we have on the wiki; can you please copy-paste the code and point out the portion of the code you think is wrong?

**Comment by larseggert** [comment]
Ah, got it. I was surprised that zero was returned while still requiring data to be sent back to the server. I'll handle that then.
