### ISSUE TITLE
AEAD example (for QUIC)?

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#51]
After a successful TLS handshake, how does one use the established TLS context to do the AEAD operations that QUIC requires? Is there any example code anywhere? (The AEAD test cases don't really help here, at least not me.)

**Comment by kazuho** [comment]
You should:
1. call `ptls_export_secret` with appropriate label and context as the arguments to extract the secret (note: context is {NULL, 0} in case of QUIC)
2. call `ptls_aead_new` to create an AEAD cipher that uses the exported secret

https://github.com/h2o/quicly/blob/master/lib/quicly.c#L463-L490 can be the example (it's the QUIC implementation that I am working on).

**Comment by larseggert** [comment]
We worked through this during the QUIC interim at IETF-99
