### ISSUE TITLE
ptls_handshake() and retransmissions

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#52]
I'm not sure if `ptls_handshake()` handles retransmissions correctly. For example, if a ClientHello is passed in twice (maybe because if got duplicated or quickly retransmitted) it seems to return `PTLS_ALERT_HANDSHAKE_FAILURE`. Is this supposed to be supported? 

(I hit this when running under valgrind, which slows things down enough so that QUIC retransmission timers fire.)

**Comment by kazuho** [comment]
Picotls is designed to work with a TCP-like bi-directional stream.

When using the library for QUIC, you would need to handle duplicates / retransmits by yourself for stream 0, the same way you wold do for other streams.

**Comment by larseggert** [comment]
OK, got it!
