### ISSUE TITLE
Malformed HRR

### ISSUE THREAD

**Issue by dcooper16** [h2o/picotls#63]
I downloaded the latest picotls code yesterday, and in testing it against my own implementation I discovered that picotls does not send a correctly formatted HRR. The HRR that picotls sends indicates a server_version of draft 21 (7f15), but it is formatted based on the syntax from draft 18.

In drafts 16, 17, and 18, HRR was defined as:
```
      struct {
          ProtocolVersion server_version;
          Extension extensions<2..2^16-1>;
      } HelloRetryRequest;
```
However, in drafts 19, 20, and 21, HRR is defined as:
```
      struct {
          ProtocolVersion server_version;
          CipherSuite cipher_suite;
          Extension extensions<2..2^16-1>;
      } HelloRetryRequest;
```

**Comment by kazuho** [comment]
Thank you for reporting the issue. Fixed in the PR above.
