### ISSUE TITLE
Series of warning when compiling minicrypto in Visual Studio

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#65]
When compiling the minicrypto lib in VS 2017, I get these warnings:

...
3>curve25519.c
3>deps\cifra\src\curve25519.tweetnacl.c(99): warning C4244: '=': conversion from 'int64_t' to 'uint8_t', possible loss of data
3>deps\cifra\src\curve25519.tweetnacl.c(201): warning C4244: 'function': conversion from 'int64_t' to 'int', possible loss of data
3>deps\cifra\src\curve25519.tweetnacl.c(202): warning C4244: 'function': conversion from 'int64_t' to 'int', possible loss of data
3>deps\cifra\src\curve25519.tweetnacl.c(221): warning C4244: 'function': conversion from 'int64_t' to 'int', possible loss of data
3>deps\cifra\src\curve25519.tweetnacl.c(222): warning C4244: 'function': conversion from 'int64_t' to 'int', possible loss of data

...
3>ccm.c
3>deps\cifra\src\ccm.c(71): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data
3>deps\cifra\src\ccm.c(82): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data

3>cbcmac.c
3>deps\cifra\src\cbcmac.c(74): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
...

They can easily be suppressed by proper type casting, but I wonder whether that is a good idea.

**Comment by kazuho** [comment]
Thank you for raising the issue.

FWIW, the files we need to compile for picotls is limited to [the files found in CMakeLists.txt](https://github.com/h2o/picotls/blob/fd180162a4f6eac509e172cd381983ef22d8fd5d/CMakeLists.txt#L12-L23).

Just skipping compilation of the non-used files might be the easiest solution.

**Comment by huitema** [comment]
ccm and cbcmac can be removed from the project, but curve25519.c loads curve25519.tweetnacl.c, which generates 4 warnings. That's not a big issue, but still...

**Comment by huitema** [comment]
Fixed by PR #68
