### ISSUE TITLE
Documentation for HRR

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#69]
I am trying to find how to implement HRR in QUIC, and I am not sure how to do such things as:

1) Tell PicoTLS to not accept the Client Hello and generate a Cookie instead. 

2) Tell the client to consume the cookie: is it sufficient to just send the TLS message through the normal handshake API?

3) Tell the server to verify the Cookie. Again, is it sufficient to pipe the messages through the handshake API?

If PicoTLS does not in fact support HRR, I suppose that the server application could generate the HRR and the cookie, and that the client could parse it and extract the Cookie extension. Then, client and server could use the handshake extension mechanism to send and verify the cookie. But that's quite a bit of work, and I would rather not have to do that...

**Comment by huitema** [comment]
So, I did a little test. I programmed my QUIC client to accept "server stateless packets", which contain stream zero input itself containing HRR. I sent the input to the handshake API. The code in PicoTLS appears to process the HRR, and I see that it calls client_handle_hello_retry_request(). But there, something goes wrong. The call to  decode_extensions(..) (lib/picotls.c, line 1317) returns an error code 50, "invalid extension". So either there is something wrong in PicoTLS or there is an issue in MozQUIC/NSS.

**Comment by huitema** [comment]
After looking a bit more at the code, I understand that the picotls spec is to:

1) Never send cookies as a server
2) Handle HRR as client if acceptable and if sent by server. In that case, the cookie is copied automatically to the new CH.

The "acceptable" notion appears to be controlled by setting the handshake property:

  handshake_properties.client.negotiate_before_key_exchange = 1;

Problem is, even with that, the processing of the HRR still fails. I tried debugging the code to understand what is going on, but the liberal use of macros makes that very hard. It seems that the cookie gets decoded, as I can see a call to iovec init with the exact size of the cookie, but just after that the macro
exits with an error PTLS_ALERT_DECODE_ERROR. I am tryong to debug further, but that's really weird.

**Comment by huitema** [comment]
I looked at the HRR Unit Test. It passes, but there is a key difference between the unit test and the test against a life server like MozQuic. In the unit test, the HRR contains just the keyshare extension, but in the test against Mozquic there are both the keyshare and a cookie, and the decoding fails.

**Comment by huitema** [comment]
Check fix in PR #70

**Comment by huitema** [comment]
PR #70 and #71 ensured that the client will properly complete the handshake if the server sends an Hello Restart Request. If a cookie is present in an HRR extension, it will be extracted and copied in the second Client Hello. That solves the highest priority problem, ensuring interop with TLS 1.3 servers that for some reason need to enforce a 3-ways handshake.

Servers may want to enforce this type of 3-ways handshake when under DOS attack. This is particularly true when TLS1.3 is used above UDP, such as with DTLS or QUIC. Picoquic server does not support this fall back to 3-ways handshake today, but we should consider it for the future. This could be treated pretty much like application-defined extensions:

* Add a flag in the server handshake properties to signal that a Cookie is required, with possibly an option to not require it when resuming a session.
* Use a Callback when a Cookie extension is received, to verify that the cookie is acceptable by the application.
* Send an HRR and clear the TLS context without performing any crypto operation if the handshake property specifies that a cookie is needed, and the cookie is either absent or invalid.

This is obviously a low priority issue -- interop was high priority. But it does not seem very hard to implement, and it would provide a nice safety valve in case of DOS attacks.

**Comment by kazuho** [comment]
Thank you for the suggestions.

I agree to the idea of adding a flag to instruct picotls to enforce a stateless retry (i.e. always send HelloRetryRequest that uses the Cookie extension to store state). It might be better to have the flag defined as part of `ptls_context_t` considering the fact that there would be no per-handshake information related to the mode.

**Comment by huitema** [comment]
Having the flag per context sounds good. Of course, the decision to accept a client hello or send an HRR will be made per connection. The callback function that makes the decision will need to see the cookie, but also the incoming IP address and port, which is a per connection variable. The application can probably retrieve that from the handshake properties + some pointer arithmetic, e.g. the "struct { super ...}" construct that you use in other places.

**Comment by kazuho** [comment]
> The callback function that makes the decision will need to see the cookie, but also the incoming IP address and port, which is a per connection variable.

Yeah. I hadn't thought of the need to verify the client address and port. Thank you for pointing that out.
Regarding how to do that, my preference goes to passing in an array of octets from the application to `ptls_handshake` (possibly as a member of the handshake properties), and use the value for checking the integrity of the cookie. That array can be a serialized form of the client address and port.

Note that in picotls we need to validate the cookie using HMAC or something. So I am suggesting that we can calculate `HMAC(key, cookie + array_of_octets_from_app)` instead of `HMAC(key, cookie)`.

Would the approach work for you?

**Comment by kazuho** [comment]
@huitema #73 implements the server side of the stateless retry. It solely relies on `ptls_handshake_properties_t` as the source of the operation mode. Please let me know if you have any concern or comments.

**Comment by kazuho** [comment]
@huitema I've merged #73. Can we close this issue now, or do you see any remaining things to be done?

**Comment by huitema** [comment]
How about I take the time to document the client side and server side use of HRR in the wiki, and then we close the issue?

**Comment by kazuho** [comment]
That would be great! Thank you very much.

**Comment by huitema** [comment]
Done. There is now documentation on HRR in the wiki.
