### ISSUE TITLE
Support draft 22?

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#90]
The README says:
~~~
At the moment, the library implements Draft 18 of the specification, including support 0-RTT resumption using PSK or PSK-DHE.
~~~
Is there a plan to support draft 22?

**Comment by kazuho** [comment]
Actually, master is on draft22. draft18 and draft21 are in dedicated branches.

**Comment by kazuho** [comment]
Updated the README. I am glad you asked it :-) Thank you.
